/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Diagnostic {
  level: string
  message: string
  span: any
}
export interface TransformOutput {
  code: string
  map?: string
  errors?: Array<Diagnostic>
  /** JSON string. */
  deps?: string
  /** JSON string. */
  modulesMapping?: string
}
export function minify(code: Buffer, opts: Buffer, signal?: AbortSignal | undefined | null): Promise<TransformOutput>
export function minifySync(code: Buffer, opts: Buffer): TransformOutput
export function transform(code: Buffer, opts: Buffer, signal?: AbortSignal | undefined | null): Promise<TransformOutput>
export function transformSync(code: Buffer, opts: Buffer): TransformOutput
