/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function minify(
  code: Buffer,
  opts: Buffer,
  signal?: AbortSignal | undefined | null
): Promise<string>;
export function minifySync(code: Buffer, opts: Buffer): string;
