/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Error {
  text: string;
}
export interface TransformOutput {
  code: string;
  errors?: Array<Error>;
}
export function minify(
  code: Buffer,
  opts: Buffer,
  signal?: AbortSignal | undefined | null
): Promise<TransformOutput>;
export function minifySync(code: Buffer, opts: Buffer): TransformOutput;
