/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Diagnostic {
  level: string;
  message: string;
  span: any;
}
export interface TransformOutput {
  code: string;
  errors?: Array<Diagnostic>;
}
export function minify(
  code: Buffer,
  opts: Buffer,
  signal?: AbortSignal | undefined | null
): Promise<TransformOutput>;
export function minifyFragment(
  code: Buffer,
  opts: Buffer,
  signal?: AbortSignal | undefined | null
): Promise<TransformOutput>;
export function minifySync(code: Buffer, opts: Buffer): TransformOutput;
export function minifyFragmentSync(code: Buffer, opts: Buffer): TransformOutput;
